#!/usr/bin/python3
# https://habr.com/ru/companies/dins/articles/584562/
import re
import sys

green_color = "\033[1;32m"
red_color = "\033[1;31m"
color_off = "\033[0m"
blue_color = "\033[1;34m"
yellow_color = "\033[1;33m"

commit_msg_filepath = sys.argv[1]

regex = r"^#\d+\s.+"

error_msg = f"""Формат сообщения комита должен соответствовать регулярному выражению {regex}
Пример: {green_color}git commit -m "#123 Работа с файлами долга\""""

with open(commit_msg_filepath, "r+") as file:
    commit_msg = file.read()
    if not re.search(regex, commit_msg):
        print(red_color + "Ошибка! Сообщение комита не содержит номер задачи")
        print(yellow_color + error_msg)
        sys.exit(1)
